'''
Author: Dietrich Sinkevitch
Program: Tech Product Search Tool
Date: 08/08/2023
Github Link: https://github.com/dytryk/techproductsearchtool
'''

from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

# defines the database table for the users; the id is autogenerated
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique = True)
    password = db.Column(db.String(100), unique = True)
    email = db.Column(db.String(100), unique = False)
    products = db.relationship('Product')

# defines the database table for the admins; the id is autogenerated, and an admin can only be added to the database through SQL commands
class Admin(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(100), unique = True)
    password = db.Column(db.String(100), unique = True)
    email = db.Column(db.String(100), unique = False)

# defines the database table for Products; each product has its own user associated with it
# One product cannot be shared by multiple users, but the same user can have multiple products saved
class Product(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(100))
    link = db.Column(db.String(1000), unique = True)
    price = db.Column(db.Integer) 
    search = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))